trigger:
  tags:
    include:
      - '*'

jobs:
- job: docker
  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
  - script: TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    displayName: Set the tag name as an environment variable

  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'dockerpush'
      repository: 'nginx-test'
      command: 'build'
      Dockerfile: './Dockerfile'
      arguments: '-t docker-push.rga.k8s.fireblink.com/nginx-test:$(TAG)'
      
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: dockerpush
      repository: nginx-test
      command: push
      tags: $(TAG)
      
#   - script: echo $VERSION_TAG
# - script: docker images
  
#- script: git describe --exact-match $(Build.SourceVersion)
#- script: echo $(Build.SourceVersion)

# steps:
# - script: git switch -c feature/fixDockerfile && ls -la
# - script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_PULL_HOST