trigger:
  branches:   
    include:
    - master
    - refs/tags/*
    exclude:
    - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: $(git describe --exact-match $(Build.SourceVersion))

steps:
  - bash: echo This is a script that could use $SYSTEM_ACCESSTOKEN
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - powershell: Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - script: echo $env:configuration
  - script: echo '$(tag)'

      
# - task: Docker@2
#   displayName: Build an image
#   inputs:
#     containerRegistry: 'dockerpush'
#     repository: 'nginx-test'
#     command: 'build'
#     Dockerfile: './Dockerfile'
#     arguments: '-t docker-push.rga.k8s.fireblink.com/nginx-test:0.1'
    
# - task: Docker@2
#   displayName: Push image
#   inputs:
#     containerRegistry: dockerpush
#     repository: nginx-test
#     command: push
#     tags: 0.1
      
# - script: docker images

# steps:
# - script: git switch -c feature/fixDockerfile && ls -la
# - script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_PULL_HOST